# RFM-LADS: Loss-Aware Robust Conditioning for Diffusion Policy Learning

RFM-LADS is a lightweight robustness extension for low-dimensional Diffusion Policy. It adds a Robust Forward Model (RFM) conditioning module and a Loss-Aware Dynamic Scheduler (LADS) to improve stable convergence, OOD hard-seed behavior, and closed-loop observation-perturbation robustness under limited demonstrations.

## Repository description

Use this text in the GitHub repository **Description** field:

> RFM-LADS implements robust low-dimensional diffusion-policy conditioning with dual perturbed-view invariance and a loss-aware dynamic scheduler for improved convergence, OOD hard-seed behavior, and closed-loop perturbation robustness.

## Method overview

RFM-LADS is designed for state-based / low-dimensional diffusion-policy learning.

The main idea is:

1. Construct two locally perturbed observation-condition views.
2. Encode both views using a lightweight task-dependent linear encoder.
3. Apply an asymmetric stop-gradient invariance loss to encourage perturbation-stable conditional features.
4. Use LADS to adapt the invariance weight from the EMA-smoothed diffusion denoising loss.
5. Use clean encoded conditions during inference. No test-time perturbation or additional denoising backbone is introduced.

The total training objective is:

```text
L_total = L_diff + W(t) * L_inv
```

where `L_diff` is the standard diffusion denoising loss, `L_inv` is the stop-gradient perturbation-invariance loss, and `W(t)` is generated by LADS.

## Files

| File | Purpose |
|---|---|
| `robust_forward_model.py` | Square-task RFM-LADS module with identity-initialized linear encoder and EMA-driven dynamic weight scheduling. |
| `diffusion_unet_lowdim_policy_rfm_lads_square.py` | Diffusion-policy wrapper for Square-style low-dimensional tasks using the external `RobustForwardModel` module. |
| `diffusion_unet_lowdim_policy_rfm_lads_pusht.py` | PushT-specific policy wrapper with task-specific RFM-LADS settings and non-identity encoder initialization. |

## Installation

This code is intended to be used inside an existing [Diffusion Policy](https://github.com/real-stanford/diffusion_policy)-style codebase.

A typical environment should include:

```bash
pip install torch diffusers einops wandb
```

You also need the original Diffusion Policy package and its dependencies.

## Integration

Copy the files into the corresponding Diffusion Policy project folders.

Example:

```bash
cp robust_forward_model.py diffusion_policy/model/common/robust_forward_model.py
cp diffusion_unet_lowdim_policy_rfm_lads_square.py diffusion_policy/policy/diffusion_unet_lowdim_policy_rfm_lads_square.py
cp diffusion_unet_lowdim_policy_rfm_lads_pusht.py diffusion_policy/policy/diffusion_unet_lowdim_policy_rfm_lads_pusht.py
```

Then update your Hydra/YAML policy target.

For Square-style tasks:

```yaml
policy:
  _target_: diffusion_policy.policy.diffusion_unet_lowdim_policy_rfm_lads_square.DiffusionUnetLowdimPolicy
```

For PushT-style tasks:

```yaml
policy:
  _target_: diffusion_policy.policy.diffusion_unet_lowdim_policy_rfm_lads_pusht.DiffusionUnetLowdimPolicy
```

The remaining policy arguments should follow the original low-dimensional Diffusion Policy configuration, including `horizon`, `obs_dim`, `action_dim`, `n_action_steps`, `n_obs_steps`, `obs_as_global_cond`, and scheduler settings.

## Task-specific settings

The provided files use the following default RFM-LADS settings.

### Square

```python
noise_std = 0.001
w_min = 0.1
w_max = 1.5
l_upper = 0.010
l_lower = 0.004
ema_decay = 0.999
identity_init = True
```

### PushT

```python
noise_std = 0.02
w_min = 0.05
w_max = 0.5
l_upper = 0.15
l_lower = 0.05
ema_decay = 0.99
identity_init = False
```

These values are task-specific defaults used in the reported experiments. For a new task, tune the perturbation scale and LADS thresholds using clean validation performance before robustness testing.

## Training

Run training through the original Diffusion Policy workspace after updating the policy target.

Example:

```bash
python train.py --config-name=train_diffusion_unet_lowdim_workspace.yaml
```

The exact command depends on your local Diffusion Policy configuration and dataset paths.

During training, the policy logs optional RFM-LADS diagnostics to Weights & Biases:

- `rfm/z_std`
- `rfm/L_inv_raw`
- `rfm/diffusion_loss`
- `rfm/ema_diff_loss`
- `rfm/current_weight`
- `rfm/total_loss`
- `rfm/L_inv_ratio`

## Inference

At inference time, RFM-LADS uses the learned encoder on clean observations:

```python
global_cond = self.rfm.encode_for_inference(obs_flat)
```

No observation perturbation is applied during inference.

## Notes on reproducibility

- This repository contains the RFM-LADS policy code only.
- Datasets, pretrained checkpoints, and environment-specific YAML files are not included unless explicitly added by the user.
- Use the same environment runner, U-Net denoising backbone, diffusion scheduler, training horizon, and evaluation scripts when comparing with the baseline.
- Do not select final checkpoints using perturbation-test results; use a clean evaluation protocol first, then evaluate perturbation robustness.

## Citation

If you use this code, please cite the corresponding manuscript:

```bibtex
@article{rfm_lads,
  title   = {RFM-LADS: Loss-Aware Robust Conditioning for Diffusion Policy Learning under Limited Demonstrations},
  author  = {Li, Zhengmiao and Zhang, Haifeng and Jia, Shijie},
  journal = {Submitted},
  year    = {2026}
}
```

## License

Please add a license file before public release. If no license is provided, others may not have permission to reuse the code.
